Dev msft 20230710
chipsalliance/caliptra-rtl pull request #149
Opened 2023-07-11 00:47 UTC by anjpar

This PR includes the following updates:

Updated timestamp of README.md
Updated timestamp of Release_Notes.md
Merged PR 113668: RDC clock gating fix for warm reset and masking for fw update reset
Merged PR 114956: Clock gating tests for mbox, DOE and KV, related bug fixes, coverage updates
Merged PR 114014: [UVM] Mailbox testcases for invalid behavior
Merged PR 114429: Merge dev-msft into MSFT internal repo
Merged PR 114881: UVM mailbox sequence fix for invalid PAUSER access check
Merged PR 114587: New soc_ifc register tests, special cases including interrupt block registers
Merged PR 114374: extended pcr_nonce from 32-bit to 256-bit
Merged PR 114111: added sha256 and hmac cov
Merged PR 113936: Promote Pipeline - TRNG L0 regression speedup
Merged PR 113911: UVM regression timeout increase
Merged PR 113388: added hmac smoke_test and update sha params
Merged PR 113659: Promote pipeline runtime optimizations
Merged PR 113010: RAS test for non fatal errors, WDT checks
Merged PR 113246: SOC_IFC - Fix for HW ERROR registers with bad rsvd fields
Merged PR 113052: New UVM mailbox test cases - inject random delays
Merged PR 113151: Fix for mbox sequence base
Merged PR 113035: SHA512 Coverage

2023-07-11 01:10 UTC, calebofearth commented
@upadhyayulakiran has some smoke test exclusions to add for the verilator check, which will be necessary for the Verilator workflow to pass.

2023-07-11 16:23 UTC, howardtr commented
> @upadhyayulakiran has some smoke test exclusions to add for the verilator check, which will be necessary for the Verilator workflow to pass.

@calebofearth - for my own understanding, could you elaborate on this?

2023-07-11 16:40 UTC, calebofearth commented
> > @upadhyayulakiran has some smoke test exclusions to add for the verilator check, which will be necessary for the Verilator workflow to pass.
> 
> @calebofearth - for my own understanding, could you elaborate on this?

Hi @howardtr , it's related to the issues discussed in https://github.com/chipsalliance/caliptra-rtl/issues/126. There are some new smoke tests being brought in from our internal repo that will exercise the same bug in Verilator and cause the workflow to break.
All we really need to do is modify [caliptra-rtl/.github/workflows/build-test-verilator.yml at dev-msft · chipsalliance/caliptra-rtl · GitHub](https://github.com/chipsalliance/caliptra-rtl/blob/dev-msft/.github/workflows/build-test-verilator.yml) to add them to the exclude list.

2023-07-11 16:46 UTC, howardtr requested changes

2023-07-11 16:46 UTC, howardtr commented on src/integration/rtl/caliptra_top.sv
> +<<<<<<< HEAD
Looks like there's a merge issue here

2023-07-11 16:47 UTC, howardtr commented
> > > @upadhyayulakiran has some smoke test exclusions to add for the verilator check, which will be necessary for the Verilator workflow to pass.
> > 
> > 
> > @calebofearth - for my own understanding, could you elaborate on this?
> 
> Hi @howardtr , it's related to the issues discussed in #126. There are some new smoke tests being brought in from our internal repo that will exercise the same bug in Verilator and cause the workflow to break. All we really need to do is modify [caliptra-rtl/.github/workflows/build-test-verilator.yml at dev-msft · chipsalliance/caliptra-rtl · GitHub](https://github.com/chipsalliance/caliptra-rtl/blob/dev-msft/.github/workflows/build-test-verilator.yml) to add them to the exclude list.

Sg!

2023-07-11 16:50 UTC, anjpar commented on src/integration/rtl/caliptra_top.sv
> +<<<<<<< HEAD
Thanks, I've pushed a fix now.

2023-07-11 17:07 UTC, anjpar commented
> > > @upadhyayulakiran has some smoke test exclusions to add for the verilator check, which will be necessary for the Verilator workflow to pass.
> > 
> > 
> > @calebofearth - for my own understanding, could you elaborate on this?
> 
> Hi @howardtr , it's related to the issues discussed in #126. There are some new smoke tests being brought in from our internal repo that will exercise the same bug in Verilator and cause the workflow to break. All we really need to do is modify [caliptra-rtl/.github/workflows/build-test-verilator.yml at dev-msft · chipsalliance/caliptra-rtl · GitHub](https://github.com/chipsalliance/caliptra-rtl/blob/dev-msft/.github/workflows/build-test-verilator.yml) to add them to the exclude list.

Exclude list updated in dev-msft branch with additional tests that needed to be excluded.

2023-07-11 17:08 UTC, anjpar commented
> @upadhyayulakiran has some smoke test exclusions to add for the verilator check, which will be necessary for the Verilator workflow to pass.

Exclude list has been updated!

2023-07-11 17:13 UTC, howardtr approved these changes

2023-07-11 19:39 UTC, calebofearth commented
> @mkurc-ant - Seemingly higher verilator version is not hitting the same issue. It is an issue though that we will have to address nevertheless. We need this bug to be filed on verilator too.
> 
> For now, we may be moving the verilator to higher version (@calebofearth is checking on this), file an internal bug on the casez/default statement to check why it was removed by @Nitsirks for RDC fixes and PR this one.
> 
> We can tackle the default one as a separate PR to see if Avirup is hitting any RDC issues with casez and default.

Just for a little more context on this comment: 
Verilator 5.002 throws a [warning](https://github.com/chipsalliance/caliptra-rtl/actions/runs/5522685192/jobs/10072632150?pr=149) about the unique casez having incomplete coverage in [soc_ifc_boot_fsm.sv](https://github.com/chipsalliance/caliptra-rtl/blob/dev-msft-20230710/src/soc_ifc/rtl/soc_ifc_boot_fsm.sv), as seen in the interactive debugger Workflow
Verilator 5.012, as seen in the Verilator smoke test workflow, does not throw the same error.

2023-07-11 23:43 UTC, calebofearth commented
In order to get the workflows passing, we need to update the 'interactive debugger' verilator version to 5.012. 
I believe that just means updating line 21 in [interactive-debugging.yml](https://github.com/chipsalliance/caliptra-rtl/blob/dev-msft-20230710/.github/workflows/interactive-debugging.yml).
We should file two separate bugs related to the unique casez warning that was fired:
1. Bug against caliptra-rtl about soc_ifc_boot_fsm to clean up the case statement
2. Bug against Verilator 5.012 not providing this warning, which would be a legitimate warning message

2023-07-11 23:49 UTC, calebofearth commented
In order to get the workflows passing, we need to update the 'interactive debugger' verilator version to 5.012.
I believe that just means updating line 21 in [interactive-debugging.yml](https://github.com/chipsalliance/caliptra-rtl/blob/dev-msft-20230710/.github/workflows/interactive-debugging.yml).
We should file two separate bugs related to the unique casez warning that was fired:

Bug against caliptra-rtl about soc_ifc_boot_fsm to clean up the case statement
Bug against Verilator 5.012 not providing this warning, which would be a legitimate warning message"

2023-07-12 00:19 UTC, calebofearth approved these changes

2023-07-12 15:51 UTC, merged