CI: use risc-v gcc 12.1.0
chipsalliance/caliptra-rtl pull request #384
Opened 2024-01-17 17:16 UTC by kgugala

This PR restores RISC-V toolchain to the version used before #377. The toolchain is hosted in the https://github.com/chipsalliance/caliptra-tools repository

2024-01-17 20:01 UTC, calebofearth requested changes
See comments

2024-01-17 20:32 UTC, kgugala commented
> For this PR, can you also add these changes:
> 
> * Remove references to 13.2.0 in the README that were added [previously](https://github.com/chipsalliance/caliptra-rtl/pull/377/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
> * Restore the GCC_PREFIX variable to the [fw_test_rom makefile](https://github.com/chipsalliance/caliptra-rtl/pull/377/files#diff-dfc0153c967744a34a054ea03d658c32e7fa8c2fb6d01b3593979cfec9e67315)
> * Remove support for riscv32-unknown-elf from the [Makefile](https://github.com/chipsalliance/caliptra-rtl/pull/377/files#diff-a5497318e3b68c6793addeaf6362dc2b350b644141ae7ae5eb10ccbb5640c177) (lines 24-26)

done

2024-01-17 20:43 UTC, calebofearth approved these changes
Thanks Karol!

2024-01-17 21:04 UTC, calebofearth commented
Resolves #382

2024-01-18 01:07 UTC, andreslagarcavilla approved these changes

2024-01-18 01:07 UTC, merged