Rev 0p8 release
chipsalliance/caliptra-rtl pull request #51
Opened 2023-04-03 19:44 UTC by anjpar

2023-04-03 19:58 UTC, korran approved these changes

2023-04-03 20:52 UTC, howardtr requested changes
Hi @anjpar - FYI I had a few open questions in https://github.com/chipsalliance/caliptra-rtl/pull/49.  (We can proceed with the merge, just wanted to make sure that it was on your radar, thanks!)

2023-04-04 18:42 UTC, anjpar commented
> Hi @anjpar - FYI I had a few open questions in #49. (We can proceed with the merge, just wanted to make sure that it was on your radar, thanks!)

Yes, they are on my radar and I'll respond to those open questions today. If you have no other concerns with this PR, can you please approve it?

2023-04-04 19:01 UTC, howardtr approved these changes

2023-04-04 23:27 UTC, anjpar commented
@Bryankel @bharatpillilli @andreslagarcavilla Can one of you complete this pull request with a regular merge?

2023-04-05 20:31 UTC, merged